<a href="https://colab.research.google.com/github/Asma-malica/ML/blob/main/ML_AdaBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
test = pd.read_csv('https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Titanic/test.csv')
train = pd.read_csv('https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Titanic/train.csv')

In [70]:
train.set_index('PassengerId',inplace = True)
test.set_index('PassengerId',inplace = True)

In [71]:
train

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [72]:
test

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...
1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [73]:
y_train = train['Survived']

In [74]:
train.drop(labels ='Survived',axis = 1 , inplace = True)

In [75]:
train.shape

(891, 10)

In [76]:
train_test  = train.append(test) #as we need large dataset we are appending the test data along with the train data
train_test.shape # so now we got 1309 datas
train_test.isnull().sum()

<ipython-input-76-7b9bae8e357a>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  train_test  = train.append(test) #as we need large dataset we are appending the test data along with the train data

Pclass         0
Name           0
Sex            0
Age          263
SibSp          0
Parch          0
Ticket         0
Fare           1
Cabin       1014
Embarked       2
dtype: int64

In [77]:
train_test.drop(columns=["Name","Ticket","Cabin","Age",'SibSp','Parch','Embarked'],axis=1,inplace=True)

In [78]:
train_test

             Pclass     Sex      Fare
PassengerId
1                 3    male    7.2500
2                 1  female   71.2833
3                 3  female    7.9250
4                 1  female   53.1000
5                 3    male    8.0500
...             ...     ...       ...
1305              3    male    8.0500
1306              1  female  108.9000
1307              3    male    7.2500
1308              3    male    8.0500
1309              3    male   22.3583

[1309 rows x 3 columns]

In [79]:
train_test["Fare"].fillna(train_test["Fare"].mean(),inplace=True)

In [80]:
train_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 1 to 1309
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pclass  1309 non-null   int64
 1   Sex     1309 non-null   object
 2   Fare    1309 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 40.9+ KB

In [81]:
train_test_dummies = pd.get_dummies(train_test,columns={'Sex'})

<ipython-input-81-d2ad4d15915e>:1: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  train_test_dummies = pd.get_dummies(train_test,columns={'Sex'})

In [82]:
train_test_dummies.shape

(1309, 4)

In [83]:
train_test_dummies.fillna(value=0.0,inplace =True)
train_test_dummies.isnull().sum()

Pclass        0
Fare          0
Sex_female    0
Sex_male      0
dtype: int64

In [84]:
x_train=train_test_dummies.values[0:891]
x_test=train_test_dummies.values[891:]

In [85]:
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
x_train_scale = scalar.fit_transform(x_train)
x_test_scale = scalar.transform(x_train)

In [86]:
from sklearn.model_selection import train_test_split
x_train_sub,x_validation_sub,y_train_sub,y_validation_sub=train_test_split(x_train_scale,y_train,random_state=0)

In [87]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [88]:
ada_boost = AdaBoostClassifier(n_estimators=20, random_state=0)
ada_boost.fit(x_train_sub, y_train_sub)

print("Accuracy score (training): {0:.3f}".format(ada_boost.score(x_train_sub, y_train_sub)))
print("Accuracy score (validation): {0:.3f}".format(ada_boost.score(x_validation_sub, y_validation_sub)))

Accuracy score (training): 0.804
Accuracy score (validation): 0.776

In [89]:
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:

    ada_boost = AdaBoostClassifier(n_estimators=20, learning_rate=learning_rate, random_state=0)
    ada_boost.fit(x_train_sub, y_train_sub)

    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb.score(x_train_sub, y_train_sub)))
    print("Accuracy score (validation): {0:.3f}".format(gb.score(x_validation_sub, y_validation_sub)))
    print()

Learning rate:  0.05
Accuracy score (training): 0.804
Accuracy score (validation): 0.776

Learning rate:  0.1
Accuracy score (training): 0.804
Accuracy score (validation): 0.776

Learning rate:  0.25
Accuracy score (training): 0.804
Accuracy score (validation): 0.776

Learning rate:  0.5
Accuracy score (training): 0.804
Accuracy score (validation): 0.776

Learning rate:  0.75
Accuracy score (training): 0.804
Accuracy score (validation): 0.776

Learning rate:  1
Accuracy score (training): 0.804
Accuracy score (validation): 0.776