<a href="https://colab.research.google.com/github/Asma-malica/ML/blob/main/ML_BOOSTING_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [234]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
df = pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Loan%20Status.csv")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [235]:
df.info() #to get the information about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [236]:
df.describe() #to get the statistical information

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [237]:
df[df['Gender'] == 'Male']

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,LP002964,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural,Y
608,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y

In [238]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [239]:
for i in df.columns:
  print(df[i].value_counts())

LP001002    1
LP002328    1
LP002305    1
LP002308    1
LP002314    1
           ..
LP001692    1
LP001693    1
LP001698    1
LP001699    1
LP002990    1
Name: Loan_ID, Length: 614, dtype: int64
Male      489
Female    112
Name: Gender, dtype: int64
Yes    398
No     213
Name: Married, dtype: int64
0     345
1     102
2     101
3+     51
Name: Dependents, dtype: int64
Graduate        480
Not Graduate    134
Name: Education, dtype: int64
No     500
Yes     82
Name: Self_Employed, dtype: int64
2500    9
4583    6
6000    6
2600    6
3333    5
       ..
3244    1
4408    1
3917    1
3992    1
7583    1
Name: ApplicantIncome, Length: 505, dtype: int64
0.0       273
2500.0      5
2083.0      5
1666.0      5
2250.0      3
         ...
2791.0      1
1010.0      1
1695.0      1
2598.0      1
240.0       1
Name: CoapplicantIncome, Length: 287, dtype: int64
120.0    20
110.0    17
100.0    15
160.0    12
187.0    12
         ..
240.0     1
214.0     1
59.0      1
166.0     1
253.0     1
Name: LoanAmount, Length: 203, dtype: int64
360.0    512
180.0     44
480.0     15
300.0     13
240.0      4
84.0       4
120.0      3
60.0       2
36.0       2
12.0       1
Name: Loan_Amount_Term, dtype: int64
1.0    475
0.0     89
Name: Credit_History, dtype: int64
Semiurban    233
Urban        202
Rural        179
Name: Property_Area, dtype: int64
Y    422
N    192
Name: Loan_Status, dtype: int64

In [240]:
for i in df.columns:
  print(df[i].nunique())

614
2
2
4
2
2
505
287
203
10
2
3
2

In [241]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [242]:
df.shape

(614, 13)

In [243]:
df.size

7982

In [244]:
df.index

RangeIndex(start=0, stop=614, step=1)

In [245]:
df['Loan_ID'].unique

<bound method Series.unique of 0      LP001002
1      LP001003
2      LP001005
3      LP001006
4      LP001008
         ...
609    LP002978
610    LP002979
611    LP002983
612    LP002984
613    LP002990
Name: Loan_ID, Length: 614, dtype: object>

In [246]:
df['Loan_ID'].value_counts()

LP001002    1
LP002328    1
LP002305    1
LP002308    1
LP002314    1
           ..
LP001692    1
LP001693    1
LP001698    1
LP001699    1
LP002990    1
Name: Loan_ID, Length: 614, dtype: int64

In [247]:
df['Gender'].nunique()

2

In [248]:
df['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [249]:
df['Gender'].value_counts()

Male      489
Female    112
Name: Gender, dtype: int64

In [250]:
# raw_null = ['Gender','Married','Dependents','Self_Employed','LoanAmount','Loan_Amount_Term','Credit_History']
# df[raw_null] = df[raw_null].replace({np.nan:df['Gender'].mode(),
#                                     np.nan:df['Married'].mode(),
#                                     np.nan:df['Dependents'].mode(),
#                                     np.nan:df['Self_Employed'].mode(),
#                                     np.nan:df['LoanAmount'].mode(),
#                                     np.nan:df['Loan_Amount_Term'].mode(),
#                                     np.nan:df['Credit_History'].mode()})
# df

for i in df.columns:
  df[i].fillna(df[i].mode()[0],inplace=True)

In [251]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,120.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [252]:
# # one hot encoding
# one_hot_encoded_data = pd.get_dummies(df)
# print(one_hot_encoded_data)

In [253]:
# Label Encoding
df["Loan_ID"],_ = pd.factorize(df["Loan_ID"])
df["Gender"],_ = pd.factorize(df["Gender"])
df["Married"],_ = pd.factorize(df["Married"])
df["Dependents"],_ = pd.factorize(df["Dependents"])
df["Education"],_ = pd.factorize(df["Education"])
df["Self_Employed"],_ = pd.factorize(df["Self_Employed"])
df["Property_Area"],_ = pd.factorize(df["Property_Area"])
df["Loan_Status"],_ = pd.factorize(df["Loan_Status"])
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,0,0,0,0,0,5849,0.0,120.0,360.0,1.0,0,0
1,1,0,1,1,0,0,4583,1508.0,128.0,360.0,1.0,1,1
2,2,0,1,0,0,1,3000,0.0,66.0,360.0,1.0,0,0
3,3,0,1,0,1,0,2583,2358.0,120.0,360.0,1.0,0,0
4,4,0,0,0,0,0,6000,0.0,141.0,360.0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,609,1,0,0,0,0,2900,0.0,71.0,360.0,1.0,1,0
610,610,0,1,3,0,0,4106,0.0,40.0,180.0,1.0,1,0
611,611,0,1,1,0,0,8072,240.0,253.0,360.0,1.0,0,0
612,612,0,1,2,0,0,7583,0.0,187.0,360.0,1.0,0,0
613,613,1,0,0,0,1,4583,0.0,133.0,360.0,0.0,2,1

In [254]:
# from sklearn.preprocessing import LabelEncoder
# lb = LabelEncoder()
# data = lb.fit_transform(df['Loan_Status'])
# data

In [255]:
# from sklearn.preprocessing import OneHotEncoder
# onehot = OneHotEncoder(sparse = False)
# df_l = np.array([df['Loan_Status']]).reshape(-1,1)
# data = onehot.fit_transform(df_l)
# data

In [256]:
# one_hot_encoded_data = pd.get_dummies(df['Loan_ID'])
# one_hot_encoded_data

In [257]:
x = df.drop(columns = ['Loan_ID','Loan_Status']).values
y = df['Loan_Status'].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size=0.3,random_state = 0)

In [258]:
x_train

array([[  0.,   0.,   0., ..., 360.,   1.,   1.],
       [  0.,   1.,   0., ..., 180.,   1.,   1.],
       [  0.,   1.,   0., ..., 360.,   1.,   2.],
       ...,
       [  0.,   1.,   3., ..., 360.,   1.,   2.],
       [  0.,   1.,   0., ..., 360.,   1.,   0.],
       [  1.,   1.,   0., ..., 360.,   1.,   2.]])

In [259]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
x_train = std.fit_transform(x_train)
x_test = std.transform(x_test)

In [260]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
rf = RandomForestClassifier(criterion = 'entropy',random_state=42)
rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [261]:
y_pred = rf.predict(x_train)
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       288
           1       1.00      1.00      1.00       141

    accuracy                           1.00       429
   macro avg       1.00      1.00      1.00       429
weighted avg       1.00      1.00      1.00       429

In [262]:
y_pred_test = rf.predict(x_test)
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.81      0.95      0.87       134
           1       0.75      0.41      0.53        51

    accuracy                           0.80       185
   macro avg       0.78      0.68      0.70       185
weighted avg       0.79      0.80      0.78       185